version: '2.1'
services:
  hazelcast:
    # hostname: hazelcast
    image: hazelcast/hazelcast:5.2.1
    ports:
    - "5701:5701"

  localstack:
    # hostname: localstack
    container_name: "organic-cache-localstack"
    image: localstack/localstack:1.4.0
    # network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # - AWS_ACCESS_KEY=test
      # - AWS_SECRET_KEY=test
      # - EDGE_PORT=4566
      - DEBUG=1
      - LS_LOG=debug
      - LAMBDA_EXECUTOR=docker-reuse
      # - LAMBDA_REMOTE_DOCKER=false
      # - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      # - HOST_TMP_FOLDER=${TMPDIR:-/tmp/localstack}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
